/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import java.util.*;
import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ABlockCrnfunc extends PCrnfunc
{
    private TTLTurborg _tLTurborg_;
    private final LinkedList<PReaction> _reaction_ = new LinkedList<PReaction>();
    private TTRTurborg _tRTurborg_;

    public ABlockCrnfunc()
    {
        // Constructor
    }

    public ABlockCrnfunc(
        @SuppressWarnings("hiding") TTLTurborg _tLTurborg_,
        @SuppressWarnings("hiding") List<?> _reaction_,
        @SuppressWarnings("hiding") TTRTurborg _tRTurborg_)
    {
        // Constructor
        setTLTurborg(_tLTurborg_);

        setReaction(_reaction_);

        setTRTurborg(_tRTurborg_);

    }

    @Override
    public Object clone()
    {
        return new ABlockCrnfunc(
            cloneNode(this._tLTurborg_),
            cloneList(this._reaction_),
            cloneNode(this._tRTurborg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockCrnfunc(this);
    }

    public TTLTurborg getTLTurborg()
    {
        return this._tLTurborg_;
    }

    public void setTLTurborg(TTLTurborg node)
    {
        if(this._tLTurborg_ != null)
        {
            this._tLTurborg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLTurborg_ = node;
    }

    public LinkedList<PReaction> getReaction()
    {
        return this._reaction_;
    }

    public void setReaction(List<?> list)
    {
        for(PReaction e : this._reaction_)
        {
            e.parent(null);
        }
        this._reaction_.clear();

        for(Object obj_e : list)
        {
            PReaction e = (PReaction) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._reaction_.add(e);
        }
    }

    public TTRTurborg getTRTurborg()
    {
        return this._tRTurborg_;
    }

    public void setTRTurborg(TTRTurborg node)
    {
        if(this._tRTurborg_ != null)
        {
            this._tRTurborg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRTurborg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tLTurborg_)
            + toString(this._reaction_)
            + toString(this._tRTurborg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tLTurborg_ == child)
        {
            this._tLTurborg_ = null;
            return;
        }

        if(this._reaction_.remove(child))
        {
            return;
        }

        if(this._tRTurborg_ == child)
        {
            this._tRTurborg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tLTurborg_ == oldChild)
        {
            setTLTurborg((TTLTurborg) newChild);
            return;
        }

        for(ListIterator<PReaction> i = this._reaction_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PReaction) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._tRTurborg_ == oldChild)
        {
            setTRTurborg((TTRTurborg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
