/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ADivideTerm extends PTerm
{
    private PPower _power_;
    private TTDiv _tDiv_;
    private PTerm _term_;

    public ADivideTerm()
    {
        // Constructor
    }

    public ADivideTerm(
        @SuppressWarnings("hiding") PPower _power_,
        @SuppressWarnings("hiding") TTDiv _tDiv_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setPower(_power_);

        setTDiv(_tDiv_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new ADivideTerm(
            cloneNode(this._power_),
            cloneNode(this._tDiv_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivideTerm(this);
    }

    public PPower getPower()
    {
        return this._power_;
    }

    public void setPower(PPower node)
    {
        if(this._power_ != null)
        {
            this._power_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._power_ = node;
    }

    public TTDiv getTDiv()
    {
        return this._tDiv_;
    }

    public void setTDiv(TTDiv node)
    {
        if(this._tDiv_ != null)
        {
            this._tDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDiv_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._power_)
            + toString(this._tDiv_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._power_ == child)
        {
            this._power_ = null;
            return;
        }

        if(this._tDiv_ == child)
        {
            this._tDiv_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._power_ == oldChild)
        {
            setPower((PPower) newChild);
            return;
        }

        if(this._tDiv_ == oldChild)
        {
            setTDiv((TTDiv) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
