/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AFactorTerm extends PTerm
{
    private PPower _power_;

    public AFactorTerm()
    {
        // Constructor
    }

    public AFactorTerm(
        @SuppressWarnings("hiding") PPower _power_)
    {
        // Constructor
        setPower(_power_);

    }

    @Override
    public Object clone()
    {
        return new AFactorTerm(
            cloneNode(this._power_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactorTerm(this);
    }

    public PPower getPower()
    {
        return this._power_;
    }

    public void setPower(PPower node)
    {
        if(this._power_ != null)
        {
            this._power_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._power_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._power_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._power_ == child)
        {
            this._power_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._power_ == oldChild)
        {
            setPower((PPower) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
