/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterEqualLogicalOperator extends PLogicalOperator
{
    private TTEqualOrGreater _tEqualOrGreater_;

    public AGreaterEqualLogicalOperator()
    {
        // Constructor
    }

    public AGreaterEqualLogicalOperator(
        @SuppressWarnings("hiding") TTEqualOrGreater _tEqualOrGreater_)
    {
        // Constructor
        setTEqualOrGreater(_tEqualOrGreater_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterEqualLogicalOperator(
            cloneNode(this._tEqualOrGreater_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterEqualLogicalOperator(this);
    }

    public TTEqualOrGreater getTEqualOrGreater()
    {
        return this._tEqualOrGreater_;
    }

    public void setTEqualOrGreater(TTEqualOrGreater node)
    {
        if(this._tEqualOrGreater_ != null)
        {
            this._tEqualOrGreater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEqualOrGreater_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tEqualOrGreater_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tEqualOrGreater_ == child)
        {
            this._tEqualOrGreater_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tEqualOrGreater_ == oldChild)
        {
            setTEqualOrGreater((TTEqualOrGreater) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
