/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterLogicalOperator extends PLogicalOperator
{
    private TTGreater _tGreater_;

    public AGreaterLogicalOperator()
    {
        // Constructor
    }

    public AGreaterLogicalOperator(
        @SuppressWarnings("hiding") TTGreater _tGreater_)
    {
        // Constructor
        setTGreater(_tGreater_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterLogicalOperator(
            cloneNode(this._tGreater_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterLogicalOperator(this);
    }

    public TTGreater getTGreater()
    {
        return this._tGreater_;
    }

    public void setTGreater(TTGreater node)
    {
        if(this._tGreater_ != null)
        {
            this._tGreater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tGreater_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tGreater_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tGreater_ == child)
        {
            this._tGreater_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tGreater_ == oldChild)
        {
            setTGreater((TTGreater) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
