/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ANotLogicalOperator extends PLogicalOperator
{
    private TTNot _tNot_;

    public ANotLogicalOperator()
    {
        // Constructor
    }

    public ANotLogicalOperator(
        @SuppressWarnings("hiding") TTNot _tNot_)
    {
        // Constructor
        setTNot(_tNot_);

    }

    @Override
    public Object clone()
    {
        return new ANotLogicalOperator(
            cloneNode(this._tNot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotLogicalOperator(this);
    }

    public TTNot getTNot()
    {
        return this._tNot_;
    }

    public void setTNot(TTNot node)
    {
        if(this._tNot_ != null)
        {
            this._tNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tNot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tNot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tNot_ == child)
        {
            this._tNot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tNot_ == oldChild)
        {
            setTNot((TTNot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
