/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AOrBoolOperator extends PBoolOperator
{
    private TTOr _tOr_;

    public AOrBoolOperator()
    {
        // Constructor
    }

    public AOrBoolOperator(
        @SuppressWarnings("hiding") TTOr _tOr_)
    {
        // Constructor
        setTOr(_tOr_);

    }

    @Override
    public Object clone()
    {
        return new AOrBoolOperator(
            cloneNode(this._tOr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrBoolOperator(this);
    }

    public TTOr getTOr()
    {
        return this._tOr_;
    }

    public void setTOr(TTOr node)
    {
        if(this._tOr_ != null)
        {
            this._tOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tOr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tOr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tOr_ == child)
        {
            this._tOr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tOr_ == oldChild)
        {
            setTOr((TTOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
