/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AParenPower extends PPower
{
    private PParen _paren_;

    public AParenPower()
    {
        // Constructor
    }

    public AParenPower(
        @SuppressWarnings("hiding") PParen _paren_)
    {
        // Constructor
        setParen(_paren_);

    }

    @Override
    public Object clone()
    {
        return new AParenPower(
            cloneNode(this._paren_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParenPower(this);
    }

    public PParen getParen()
    {
        return this._paren_;
    }

    public void setParen(PParen node)
    {
        if(this._paren_ != null)
        {
            this._paren_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paren_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paren_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paren_ == child)
        {
            this._paren_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paren_ == oldChild)
        {
            setParen((PParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
