/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ATimeOption extends POption
{
    private TTTime _tTime_;

    public ATimeOption()
    {
        // Constructor
    }

    public ATimeOption(
        @SuppressWarnings("hiding") TTTime _tTime_)
    {
        // Constructor
        setTTime(_tTime_);

    }

    @Override
    public Object clone()
    {
        return new ATimeOption(
            cloneNode(this._tTime_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimeOption(this);
    }

    public TTTime getTTime()
    {
        return this._tTime_;
    }

    public void setTTime(TTTime node)
    {
        if(this._tTime_ != null)
        {
            this._tTime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tTime_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tTime_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tTime_ == child)
        {
            this._tTime_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tTime_ == oldChild)
        {
            setTTime((TTTime) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
