/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.lexer;

import java.io.*;

@SuppressWarnings("serial")
public interface IPushbackReader
{
    int read() throws IOException;
    void unread(int c) throws IOException;
}
