/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.lexer;

import java.io.*;
import com.company.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private final IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private final PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPlus(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMinus(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMult(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDiv(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEqual(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTPower(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLambda(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTTime(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTCycle(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSpace(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTInt(text, line, pos); }
    Token new11(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTString(text, line, pos); }
    Token new12(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTFloat(text, line, pos); }
    Token new13(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEqualOrGreater(text, line, pos); }
    Token new14(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEqualOrSmaller(text, line, pos); }
    Token new15(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNot(text, line, pos); }
    Token new16(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNotEqual(text, line, pos); }
    Token new17(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTAnd(text, line, pos); }
    Token new18(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTOr(text, line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLogicalEqual(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTGreater(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSmaller(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTComma(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTColon(text, line, pos); }
    Token new24(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSemicolon(text, line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLParen(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTRParen(text, line, pos); }
    Token new27(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTLTurborg(text, line, pos); }
    Token new28(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTRTurborg(text, line, pos); }
    Token new29(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTArrow(text, line, pos); }
    Token new30(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDoubleArrow(text, line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTNewl(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDot(text, line, pos); }
    Token new33(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTComments(text, line, pos); }
    Token new34(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBlank(text, line, pos); }
    Token new35(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEol(text, line, pos); }
    Token new36(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTAddmol(text, line, pos); }
    Token new37(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTRemmol(text, line, pos); }
    Token new38(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTInitializedcl(text, line, pos); }
    Token new39(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSampledcl(text, line, pos); }
    Token new40(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSpeciesdcl(text, line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTRatedcl(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTFuncdcl(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTFloatType(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTIntType(text, line, pos); }
    Token new45(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTRateType(text, line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTWhiledcl(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTCrndcl(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTProtocoldcl(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEquilibratedcl(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTMixdcl(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTDisposedcl(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTSplitdcl(text, line, pos); }
    Token new53(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTFordcl(text, line, pos); }
    Token new54(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTVoiddcl(text, line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTBydcl(text, line, pos); }
    Token new56(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTEach(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static final int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {38, 38, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 48, 15}, {49, 57, 16}, {58, 58, 17}, {59, 59, 18}, {60, 60, 19}, {61, 61, 20}, {62, 62, 21}, {65, 65, 22}, {66, 66, 23}, {67, 67, 24}, {68, 68, 25}, {69, 69, 26}, {70, 70, 27}, {71, 72, 23}, {73, 73, 28}, {74, 76, 23}, {77, 77, 29}, {78, 78, 23}, {79, 79, 30}, {80, 80, 31}, {81, 81, 23}, {82, 82, 32}, {83, 83, 33}, {84, 86, 23}, {87, 87, 34}, {88, 90, 23}, {97, 97, 35}, {98, 98, 36}, {99, 100, 23}, {101, 101, 37}, {102, 102, 38}, {103, 104, 23}, {105, 105, 39}, {106, 109, 23}, {110, 110, 40}, {111, 111, 41}, {112, 113, 23}, {114, 114, 42}, {115, 117, 23}, {118, 118, 43}, {119, 119, 44}, {120, 122, 23}, {123, 123, 45}, {124, 124, 46}, {125, 125, 47}, },
            {{9, 9, 1}, {10, 10, 48}, {32, 32, 49}, {123, 123, 45}, {125, 125, 47}, },
            {{9, 125, -3}, },
            {{10, 10, 50}, },
            {{9, 10, -3}, {32, 33, -2}, {40, 45, -2}, {47, 47, 51}, {58, 59, -2}, {60, 60, 52}, {61, 61, 53}, {62, 62, 54}, {67, 67, 55}, {84, 84, 56}, {98, 98, 57}, {99, 99, 58}, {101, 101, 59}, {102, 102, 60}, {110, 110, 61}, {116, 116, 62}, {123, 125, -3}, },
            {{61, 61, 63}, },
            {{38, 38, 64}, },
            {{32, 32, 65}, },
            {{32, 32, 66}, },
            {{32, 32, 67}, {42, 42, 68}, },
            {{32, 32, 69}, },
            {{32, 32, 70}, },
            {{32, 32, 71}, {62, 62, 72}, },
            {{32, 32, 73}, },
            {{32, 32, 74}, {42, 42, 75}, },
            {{46, 46, 76}, },
            {{46, 46, 76}, {48, 57, 77}, },
            {{32, 32, 78}, },
            {{32, 32, 79}, {92, 92, 80}, },
            {{32, 32, 81}, {45, 45, 82}, {61, 61, 83}, },
            {{32, 32, 84}, {61, 61, 85}, {62, 62, 86}, },
            {{32, 32, 87}, {61, 61, 88}, },
            {{48, 57, 89}, {65, 77, 90}, {78, 78, 91}, {79, 90, 90}, {97, 99, 90}, {100, 100, 92}, {101, 122, 90}, },
            {{48, 57, 89}, {65, 90, 90}, {97, 122, 90}, },
            {{48, 57, 89}, {65, 81, 90}, {82, 82, 93}, {83, 90, 90}, {97, 122, 90}, },
            {{48, 90, -25}, {97, 104, 90}, {105, 105, 94}, {106, 122, 90}, },
            {{48, 90, -25}, {97, 112, 90}, {113, 113, 95}, {114, 122, 90}, },
            {{48, 90, -25}, {97, 107, 90}, {108, 108, 96}, {109, 116, 90}, {117, 117, 97}, {118, 122, 90}, },
            {{48, 90, -25}, {97, 109, 90}, {110, 110, 98}, {111, 122, 90}, },
            {{48, 104, -27}, {105, 105, 99}, {106, 122, 90}, },
            {{48, 81, -26}, {82, 82, 100}, {83, 122, -26}, },
            {{48, 90, -25}, {97, 113, 90}, {114, 114, 101}, {115, 122, 90}, },
            {{48, 90, -25}, {97, 97, 102}, {98, 100, 90}, {101, 101, 103}, {102, 122, 90}, },
            {{48, 90, -25}, {97, 97, 104}, {98, 111, 90}, {112, 112, 105}, {113, 122, 90}, },
            {{48, 90, -25}, {97, 103, 90}, {104, 104, 106}, {105, 122, 90}, },
            {{48, 109, -30}, {110, 110, 107}, {111, 122, 90}, },
            {{48, 90, -25}, {97, 120, 90}, {121, 121, 108}, {122, 122, 90}, },
            {{48, 90, -25}, {97, 97, 109}, {98, 122, 90}, },
            {{48, 108, -29}, {109, 110, 90}, {111, 111, 110}, {112, 122, 90}, },
            {{48, 109, -30}, {110, 110, 111}, {111, 122, 90}, },
            {{48, 90, -25}, {97, 110, 90}, {111, 111, 112}, {112, 122, 90}, },
            {{48, 113, -33}, {114, 114, 113}, {115, 122, 90}, },
            {{48, 90, -25}, {97, 97, 114}, {98, 122, 90}, },
            {{48, 110, -42}, {111, 111, 115}, {112, 122, 90}, },
            {{48, 122, -36}, },
            {{9, 9, 116}, {10, 10, 117}, {32, 32, 118}, },
            {{124, 124, 119}, },
            {{9, 9, 120}, {10, 10, 121}, {32, 32, 122}, },
            {{9, 125, -3}, },
            {{9, 125, -3}, },
            {},
            {{32, 32, 74}, },
            {{45, 61, -21}, },
            {{32, 32, 84}, {62, 62, 86}, },
            {{61, 61, 88}, },
            {{32, 32, 123}, },
            {{32, 32, 124}, },
            {{121, 121, 125}, },
            {{32, 32, 123}, },
            {{97, 97, 126}, },
            {{111, 111, 127}, },
            {{111, 111, 128}, },
            {{32, 32, 124}, },
            {{32, 32, 129}, },
            {{32, 32, 130}, },
            {{32, 32, 65}, },
            {{32, 32, 66}, },
            {{32, 32, 67}, },
            {{32, 32, 131}, },
            {{32, 32, 69}, },
            {{32, 32, 70}, },
            {{32, 32, 71}, },
            {{32, 32, 132}, },
            {{32, 32, 73}, },
            {{32, 32, 74}, },
            {{0, 41, 133}, {42, 42, 134}, {43, 65535, 133}, },
            {{48, 57, 135}, },
            {{46, 57, -18}, },
            {{32, 32, 78}, },
            {{32, 92, -20}, },
            {{110, 110, 136}, },
            {{32, 32, 81}, },
            {{62, 62, 137}, },
            {{32, 32, 138}, },
            {{32, 32, 84}, },
            {{32, 32, 139}, },
            {{32, 32, 140}, },
            {{32, 32, 87}, },
            {{32, 32, 141}, },
            {{48, 122, -25}, },
            {{48, 122, -25}, },
            {{48, 57, 89}, {65, 67, 90}, {68, 68, 142}, {69, 90, 90}, {97, 122, 90}, },
            {{48, 90, -25}, {97, 99, 90}, {100, 100, 143}, {101, 122, 90}, },
            {{48, 77, -24}, {78, 78, 144}, {79, 90, 90}, {97, 122, 90}, },
            {{48, 90, -25}, {97, 114, 90}, {115, 115, 145}, {116, 122, 90}, },
            {{48, 90, -25}, {97, 116, 90}, {117, 117, 146}, {118, 122, 90}, },
            {{48, 110, -42}, {111, 111, 147}, {112, 122, 90}, },
            {{48, 109, -30}, {110, 110, 148}, {111, 122, 90}, },
            {{48, 104, -27}, {105, 105, 149}, {106, 115, 90}, {116, 116, 150}, {117, 122, 90}, },
            {{48, 90, -25}, {97, 119, 90}, {120, 120, 151}, {121, 122, 90}, },
            {{32, 32, 152}, {48, 122, -25}, },
            {{48, 110, -42}, {111, 111, 153}, {112, 122, 90}, },
            {{48, 90, -25}, {97, 115, 90}, {116, 116, 154}, {117, 122, 90}, },
            {{48, 90, -25}, {97, 108, 90}, {109, 109, 155}, {110, 122, 90}, },
            {{48, 108, -105}, {109, 109, 156}, {110, 122, 90}, },
            {{48, 90, -25}, {97, 100, 90}, {101, 101, 157}, {102, 107, 90}, {108, 108, 158}, {109, 122, 90}, },
            {{48, 104, -27}, {105, 105, 159}, {106, 122, 90}, },
            {{48, 99, -94}, {100, 100, 160}, {101, 122, 90}, },
            {{32, 32, 161}, {48, 122, -25}, },
            {{48, 90, -25}, {97, 98, 90}, {99, 99, 162}, {100, 122, 90}, },
            {{48, 113, -33}, {114, 114, 163}, {115, 122, 90}, },
            {{48, 115, -104}, {116, 122, -100}, },
            {{48, 115, -104}, {116, 116, 164}, {117, 122, 90}, },
            {{32, 32, 165}, {48, 122, -25}, },
            {{48, 115, -104}, {116, 116, 166}, {117, 122, 90}, },
            {{48, 104, -27}, {105, 105, 167}, {106, 122, 90}, },
            {{9, 32, -47}, },
            {{9, 32, -47}, },
            {{9, 32, -47}, },
            {{32, 32, 168}, },
            {{9, 32, -49}, },
            {{9, 32, -49}, },
            {{9, 32, -49}, },
            {{32, 32, 123}, },
            {{32, 32, 124}, },
            {{32, 32, 161}, },
            {{99, 99, 169}, },
            {{114, 114, 170}, },
            {{116, 116, 171}, },
            {{32, 32, 129}, },
            {{32, 32, 130}, },
            {{32, 32, 131}, },
            {{32, 32, 132}, },
            {{0, 65535, -77}, },
            {{0, 41, 172}, {42, 42, 134}, {43, 46, 172}, {47, 47, 173}, {48, 65535, 172}, },
            {{48, 57, 135}, },
            {{92, 92, 80}, },
            {{32, 32, 174}, },
            {{32, 32, 138}, },
            {{32, 32, 139}, },
            {{32, 32, 140}, },
            {{32, 32, 141}, },
            {{32, 32, 175}, {48, 122, -25}, },
            {{48, 57, 89}, {65, 76, 90}, {77, 77, 176}, {78, 90, 90}, {97, 122, 90}, },
            {{32, 32, 177}, {48, 122, -25}, },
            {{48, 90, -25}, {97, 111, 90}, {112, 112, 178}, {113, 122, 90}, },
            {{48, 104, -27}, {105, 105, 179}, {106, 122, 90}, },
            {{48, 90, -25}, {97, 97, 180}, {98, 122, 90}, },
            {{48, 98, -111}, {99, 99, 181}, {100, 122, 90}, },
            {{48, 115, -104}, {116, 116, 182}, {117, 122, 90}, },
            {{32, 32, 183}, {48, 122, -25}, },
            {{32, 32, 184}, {48, 122, -25}, },
            {{32, 32, 152}, },
            {{48, 115, -104}, {116, 116, 185}, {117, 122, 90}, },
            {{48, 100, -107}, {101, 101, 186}, {102, 122, 90}, },
            {{48, 76, -145}, {77, 77, 187}, {78, 122, -145}, },
            {{48, 111, -147}, {112, 112, 188}, {113, 122, 90}, },
            {{48, 98, -111}, {99, 99, 189}, {100, 122, 90}, },
            {{48, 104, -27}, {105, 105, 190}, {106, 122, 90}, },
            {{48, 107, -29}, {108, 108, 191}, {109, 122, 90}, },
            {{32, 32, 192}, {48, 122, -25}, },
            {{32, 32, 161}, },
            {{48, 103, -36}, {104, 104, 193}, {105, 122, 90}, },
            {{32, 32, 194}, {48, 122, -25}, },
            {{32, 32, 195}, {48, 57, 89}, {61, 61, 63}, {65, 122, -25}, },
            {{32, 32, 165}, },
            {{48, 100, -107}, {101, 101, 196}, {102, 122, 90}, },
            {{48, 99, -94}, {100, 100, 197}, {101, 122, 90}, },
            {{32, 32, 168}, },
            {{104, 104, 198}, },
            {{32, 32, 194}, },
            {{32, 32, 195}, {61, 61, 63}, },
            {{0, 41, 199}, {42, 42, 200}, {43, 65535, 199}, },
            {},
            {{32, 32, 174}, },
            {{32, 32, 175}, },
            {{48, 110, -42}, {111, 111, 201}, {112, 122, 90}, },
            {{32, 32, 177}, },
            {{48, 110, -42}, {111, 111, 202}, {112, 122, 90}, },
            {{48, 107, -29}, {108, 108, 203}, {109, 122, 90}, },
            {{48, 115, -104}, {116, 116, 204}, {117, 122, 90}, },
            {{32, 32, 205}, {48, 122, -25}, },
            {{48, 104, -27}, {105, 105, 206}, {106, 122, 90}, },
            {{32, 32, 183}, },
            {{32, 32, 184}, },
            {{48, 110, -42}, {111, 111, 207}, {112, 122, 90}, },
            {{32, 32, 208}, {48, 122, -25}, },
            {{48, 110, -42}, {111, 111, 209}, {112, 122, 90}, },
            {{48, 107, -29}, {108, 108, 210}, {109, 122, 90}, },
            {{48, 104, -27}, {105, 105, 211}, {106, 122, 90}, },
            {{48, 115, -104}, {116, 116, 212}, {117, 122, 90}, },
            {{48, 100, -107}, {101, 101, 213}, {102, 122, 90}, },
            {{32, 32, 192}, },
            {{32, 32, 214}, {48, 122, -25}, },
            {{32, 32, 194}, },
            {{32, 61, -173}, },
            {{32, 32, 215}, {48, 122, -25}, },
            {{32, 32, 216}, {48, 122, -25}, },
            {{32, 32, 214}, },
            {{0, 65535, -174}, },
            {{0, 41, 172}, {42, 42, 200}, {43, 65535, -136}, },
            {{48, 107, -29}, {108, 108, 217}, {109, 122, 90}, },
            {{48, 114, -96}, {115, 115, 218}, {116, 122, 90}, },
            {{48, 104, -27}, {105, 105, 219}, {106, 122, 90}, },
            {{32, 32, 220}, {48, 122, -25}, },
            {{32, 32, 205}, },
            {{48, 90, -25}, {97, 97, 221}, {98, 122, 90}, },
            {{48, 98, -111}, {99, 99, 222}, {100, 122, 90}, },
            {{32, 32, 208}, },
            {{48, 107, -29}, {108, 108, 223}, {109, 122, 90}, },
            {{48, 100, -107}, {101, 101, 224}, {102, 122, 90}, },
            {{48, 100, -107}, {101, 101, 225}, {102, 122, 90}, },
            {{32, 32, 226}, {48, 122, -25}, },
            {{32, 32, 227}, {48, 122, -25}, },
            {{32, 32, 214}, },
            {{32, 32, 215}, },
            {{32, 32, 216}, },
            {{32, 32, 228}, {48, 122, -25}, },
            {{48, 100, -107}, {101, 101, 229}, {102, 122, 90}, },
            {{48, 90, -25}, {97, 97, 90}, {98, 98, 230}, {99, 122, 90}, },
            {{32, 32, 220}, },
            {{48, 107, -29}, {108, 108, 231}, {109, 122, 90}, },
            {{48, 110, -42}, {111, 111, 232}, {112, 122, 90}, },
            {{32, 32, 233}, {48, 122, -25}, },
            {{32, 32, 234}, {48, 122, -25}, },
            {{32, 32, 235}, {48, 122, -25}, },
            {{32, 32, 226}, },
            {{32, 32, 227}, },
            {{32, 32, 228}, },
            {{32, 32, 236}, {48, 122, -25}, },
            {{48, 113, -33}, {114, 114, 237}, {115, 122, 90}, },
            {{48, 104, -27}, {105, 105, 238}, {106, 122, 90}, },
            {{48, 107, -29}, {108, 108, 239}, {109, 122, 90}, },
            {{32, 32, 233}, },
            {{32, 32, 234}, },
            {{32, 32, 235}, },
            {{32, 32, 236}, },
            {{48, 90, -25}, {97, 97, 240}, {98, 122, 90}, },
            {{48, 90, -25}, {97, 121, 90}, {122, 122, 241}, },
            {{32, 32, 242}, {48, 122, -25}, },
            {{48, 115, -104}, {116, 116, 243}, {117, 122, 90}, },
            {{48, 100, -107}, {101, 101, 244}, {102, 122, 90}, },
            {{32, 32, 242}, },
            {{48, 100, -107}, {101, 101, 245}, {102, 122, 90}, },
            {{32, 32, 246}, {48, 122, -25}, },
            {{32, 32, 247}, {48, 122, -25}, },
            {{32, 32, 246}, },
            {{32, 32, 247}, },
        }
    };*/

    private static final int[][] accept;
/*  {
        // INITIAL
        {9, 31, 31, 35, 9, 15, -1, 25, 26, 2, 0, 22, 1, 32, 3, 10, 10, 23, 24, 21, 4, 20, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 27, -1, 28, 31, 31, 35, 3, -1, 4, -1, 8, 7, -1, 8, -1, -1, -1, 7, 16, 17, 25, 26, 2, 5, 0, 22, 1, 29, 32, 3, -1, 12, 10, 23, 24, -1, 21, -1, 14, 4, 19, 6, 20, 13, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 27, 27, 27, 18, 28, 28, 28, 8, 7, 55, -1, -1, -1, 16, 17, 5, 29, -1, -1, 12, 24, 30, 14, 19, 6, 13, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 18, 11, 11, 11, 11, 11, 11, 11, 11, 55, 11, 11, 11, 18, 11, 11, 18, -1, 53, 15, -1, 33, 30, 17, 11, 47, 11, 11, 11, 11, 11, 44, 50, 11, 11, 11, 11, 11, 11, 11, 17, 11, 53, 15, 11, 11, 56, -1, -1, 11, 11, 11, 11, 42, 11, 11, 41, 11, 11, 11, 11, 11, 56, 45, 54, 11, 11, 11, 43, 11, 11, 11, 11, 11, 52, 46, 36, 11, 11, 11, 11, 37, 39, 40, 51, 11, 11, 11, 11, 11, 48, 11, 11, 11, 38, 49, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private final int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
