/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AAndBoolOperator extends PBoolOperator
{
    private TTAnd _tAnd_;

    public AAndBoolOperator()
    {
        // Constructor
    }

    public AAndBoolOperator(
        @SuppressWarnings("hiding") TTAnd _tAnd_)
    {
        // Constructor
        setTAnd(_tAnd_);

    }

    @Override
    public Object clone()
    {
        return new AAndBoolOperator(
            cloneNode(this._tAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndBoolOperator(this);
    }

    public TTAnd getTAnd()
    {
        return this._tAnd_;
    }

    public void setTAnd(TTAnd node)
    {
        if(this._tAnd_ != null)
        {
            this._tAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tAnd_ == child)
        {
            this._tAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tAnd_ == oldChild)
        {
            setTAnd((TTAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
