/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ACommaTitrationContinue extends PTitrationContinue
{
    private TTComma _tComma_;

    public ACommaTitrationContinue()
    {
        // Constructor
    }

    public ACommaTitrationContinue(
        @SuppressWarnings("hiding") TTComma _tComma_)
    {
        // Constructor
        setTComma(_tComma_);

    }

    @Override
    public Object clone()
    {
        return new ACommaTitrationContinue(
            cloneNode(this._tComma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaTitrationContinue(this);
    }

    public TTComma getTComma()
    {
        return this._tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(this._tComma_ != null)
        {
            this._tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tComma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tComma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tComma_ == child)
        {
            this._tComma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
