/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AEqualLogicalOperator extends PLogicalOperator
{
    private TTLogicalEqual _tLogicalEqual_;

    public AEqualLogicalOperator()
    {
        // Constructor
    }

    public AEqualLogicalOperator(
        @SuppressWarnings("hiding") TTLogicalEqual _tLogicalEqual_)
    {
        // Constructor
        setTLogicalEqual(_tLogicalEqual_);

    }

    @Override
    public Object clone()
    {
        return new AEqualLogicalOperator(
            cloneNode(this._tLogicalEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualLogicalOperator(this);
    }

    public TTLogicalEqual getTLogicalEqual()
    {
        return this._tLogicalEqual_;
    }

    public void setTLogicalEqual(TTLogicalEqual node)
    {
        if(this._tLogicalEqual_ != null)
        {
            this._tLogicalEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLogicalEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tLogicalEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tLogicalEqual_ == child)
        {
            this._tLogicalEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tLogicalEqual_ == oldChild)
        {
            setTLogicalEqual((TTLogicalEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
