/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AIntType extends PType
{
    private TTIntType _tIntType_;

    public AIntType()
    {
        // Constructor
    }

    public AIntType(
        @SuppressWarnings("hiding") TTIntType _tIntType_)
    {
        // Constructor
        setTIntType(_tIntType_);

    }

    @Override
    public Object clone()
    {
        return new AIntType(
            cloneNode(this._tIntType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntType(this);
    }

    public TTIntType getTIntType()
    {
        return this._tIntType_;
    }

    public void setTIntType(TTIntType node)
    {
        if(this._tIntType_ != null)
        {
            this._tIntType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tIntType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tIntType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tIntType_ == child)
        {
            this._tIntType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tIntType_ == oldChild)
        {
            setTIntType((TTIntType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
