/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleRates extends PRates
{
    private TTString _tString_;
    private TTEqual _tEqual_;
    private TTFloat _tFloat_;
    private TTComma _tComma_;
    private PRates _rates_;

    public AMultipleRates()
    {
        // Constructor
    }

    public AMultipleRates(
        @SuppressWarnings("hiding") TTString _tString_,
        @SuppressWarnings("hiding") TTEqual _tEqual_,
        @SuppressWarnings("hiding") TTFloat _tFloat_,
        @SuppressWarnings("hiding") TTComma _tComma_,
        @SuppressWarnings("hiding") PRates _rates_)
    {
        // Constructor
        setTString(_tString_);

        setTEqual(_tEqual_);

        setTFloat(_tFloat_);

        setTComma(_tComma_);

        setRates(_rates_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleRates(
            cloneNode(this._tString_),
            cloneNode(this._tEqual_),
            cloneNode(this._tFloat_),
            cloneNode(this._tComma_),
            cloneNode(this._rates_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleRates(this);
    }

    public TTString getTString()
    {
        return this._tString_;
    }

    public void setTString(TTString node)
    {
        if(this._tString_ != null)
        {
            this._tString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tString_ = node;
    }

    public TTEqual getTEqual()
    {
        return this._tEqual_;
    }

    public void setTEqual(TTEqual node)
    {
        if(this._tEqual_ != null)
        {
            this._tEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEqual_ = node;
    }

    public TTFloat getTFloat()
    {
        return this._tFloat_;
    }

    public void setTFloat(TTFloat node)
    {
        if(this._tFloat_ != null)
        {
            this._tFloat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tFloat_ = node;
    }

    public TTComma getTComma()
    {
        return this._tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(this._tComma_ != null)
        {
            this._tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tComma_ = node;
    }

    public PRates getRates()
    {
        return this._rates_;
    }

    public void setRates(PRates node)
    {
        if(this._rates_ != null)
        {
            this._rates_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rates_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tString_)
            + toString(this._tEqual_)
            + toString(this._tFloat_)
            + toString(this._tComma_)
            + toString(this._rates_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tString_ == child)
        {
            this._tString_ = null;
            return;
        }

        if(this._tEqual_ == child)
        {
            this._tEqual_ = null;
            return;
        }

        if(this._tFloat_ == child)
        {
            this._tFloat_ = null;
            return;
        }

        if(this._tComma_ == child)
        {
            this._tComma_ = null;
            return;
        }

        if(this._rates_ == child)
        {
            this._rates_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tString_ == oldChild)
        {
            setTString((TTString) newChild);
            return;
        }

        if(this._tEqual_ == oldChild)
        {
            setTEqual((TTEqual) newChild);
            return;
        }

        if(this._tFloat_ == oldChild)
        {
            setTFloat((TTFloat) newChild);
            return;
        }

        if(this._tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(this._rates_ == oldChild)
        {
            setRates((PRates) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
