/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ANotEqualLogicalOperator extends PLogicalOperator
{
    private TTNotEqual _tNotEqual_;

    public ANotEqualLogicalOperator()
    {
        // Constructor
    }

    public ANotEqualLogicalOperator(
        @SuppressWarnings("hiding") TTNotEqual _tNotEqual_)
    {
        // Constructor
        setTNotEqual(_tNotEqual_);

    }

    @Override
    public Object clone()
    {
        return new ANotEqualLogicalOperator(
            cloneNode(this._tNotEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotEqualLogicalOperator(this);
    }

    public TTNotEqual getTNotEqual()
    {
        return this._tNotEqual_;
    }

    public void setTNotEqual(TTNotEqual node)
    {
        if(this._tNotEqual_ != null)
        {
            this._tNotEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tNotEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tNotEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tNotEqual_ == child)
        {
            this._tNotEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tNotEqual_ == oldChild)
        {
            setTNotEqual((TTNotEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
