/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ARemoveTitrationdcl extends PTitrationdcl
{
    private TTRemmol _tRemmol_;

    public ARemoveTitrationdcl()
    {
        // Constructor
    }

    public ARemoveTitrationdcl(
        @SuppressWarnings("hiding") TTRemmol _tRemmol_)
    {
        // Constructor
        setTRemmol(_tRemmol_);

    }

    @Override
    public Object clone()
    {
        return new ARemoveTitrationdcl(
            cloneNode(this._tRemmol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARemoveTitrationdcl(this);
    }

    public TTRemmol getTRemmol()
    {
        return this._tRemmol_;
    }

    public void setTRemmol(TTRemmol node)
    {
        if(this._tRemmol_ != null)
        {
            this._tRemmol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRemmol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tRemmol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tRemmol_ == child)
        {
            this._tRemmol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tRemmol_ == oldChild)
        {
            setTRemmol((TTRemmol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
