/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ASingleLogicalExprs extends PLogicalExprs
{
    private PLogicalExpr _logicalExpr_;

    public ASingleLogicalExprs()
    {
        // Constructor
    }

    public ASingleLogicalExprs(
        @SuppressWarnings("hiding") PLogicalExpr _logicalExpr_)
    {
        // Constructor
        setLogicalExpr(_logicalExpr_);

    }

    @Override
    public Object clone()
    {
        return new ASingleLogicalExprs(
            cloneNode(this._logicalExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleLogicalExprs(this);
    }

    public PLogicalExpr getLogicalExpr()
    {
        return this._logicalExpr_;
    }

    public void setLogicalExpr(PLogicalExpr node)
    {
        if(this._logicalExpr_ != null)
        {
            this._logicalExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicalExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicalExpr_ == child)
        {
            this._logicalExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicalExpr_ == oldChild)
        {
            setLogicalExpr((PLogicalExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
