/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ASpeciesSamplebody extends PSamplebody
{
    private PSpecies _species_;

    public ASpeciesSamplebody()
    {
        // Constructor
    }

    public ASpeciesSamplebody(
        @SuppressWarnings("hiding") PSpecies _species_)
    {
        // Constructor
        setSpecies(_species_);

    }

    @Override
    public Object clone()
    {
        return new ASpeciesSamplebody(
            cloneNode(this._species_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpeciesSamplebody(this);
    }

    public PSpecies getSpecies()
    {
        return this._species_;
    }

    public void setSpecies(PSpecies node)
    {
        if(this._species_ != null)
        {
            this._species_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._species_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._species_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._species_ == child)
        {
            this._species_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._species_ == oldChild)
        {
            setSpecies((PSpecies) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
