/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ATwoWayArrows extends PArrows
{
    private TTDoubleArrow _tDoubleArrow_;
    private PReactant _reactant_;
    private TTComma _tComma_;
    private PReactionRateI _reactionRateI_;
    private TTColon _tColon_;
    private PReactionRateIi _reactionRateIi_;
    private TTSemicolon _tSemicolon_;

    public ATwoWayArrows()
    {
        // Constructor
    }

    public ATwoWayArrows(
        @SuppressWarnings("hiding") TTDoubleArrow _tDoubleArrow_,
        @SuppressWarnings("hiding") PReactant _reactant_,
        @SuppressWarnings("hiding") TTComma _tComma_,
        @SuppressWarnings("hiding") PReactionRateI _reactionRateI_,
        @SuppressWarnings("hiding") TTColon _tColon_,
        @SuppressWarnings("hiding") PReactionRateIi _reactionRateIi_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setTDoubleArrow(_tDoubleArrow_);

        setReactant(_reactant_);

        setTComma(_tComma_);

        setReactionRateI(_reactionRateI_);

        setTColon(_tColon_);

        setReactionRateIi(_reactionRateIi_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new ATwoWayArrows(
            cloneNode(this._tDoubleArrow_),
            cloneNode(this._reactant_),
            cloneNode(this._tComma_),
            cloneNode(this._reactionRateI_),
            cloneNode(this._tColon_),
            cloneNode(this._reactionRateIi_),
            cloneNode(this._tSemicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATwoWayArrows(this);
    }

    public TTDoubleArrow getTDoubleArrow()
    {
        return this._tDoubleArrow_;
    }

    public void setTDoubleArrow(TTDoubleArrow node)
    {
        if(this._tDoubleArrow_ != null)
        {
            this._tDoubleArrow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tDoubleArrow_ = node;
    }

    public PReactant getReactant()
    {
        return this._reactant_;
    }

    public void setReactant(PReactant node)
    {
        if(this._reactant_ != null)
        {
            this._reactant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reactant_ = node;
    }

    public TTComma getTComma()
    {
        return this._tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(this._tComma_ != null)
        {
            this._tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tComma_ = node;
    }

    public PReactionRateI getReactionRateI()
    {
        return this._reactionRateI_;
    }

    public void setReactionRateI(PReactionRateI node)
    {
        if(this._reactionRateI_ != null)
        {
            this._reactionRateI_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reactionRateI_ = node;
    }

    public TTColon getTColon()
    {
        return this._tColon_;
    }

    public void setTColon(TTColon node)
    {
        if(this._tColon_ != null)
        {
            this._tColon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tColon_ = node;
    }

    public PReactionRateIi getReactionRateIi()
    {
        return this._reactionRateIi_;
    }

    public void setReactionRateIi(PReactionRateIi node)
    {
        if(this._reactionRateIi_ != null)
        {
            this._reactionRateIi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reactionRateIi_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tDoubleArrow_)
            + toString(this._reactant_)
            + toString(this._tComma_)
            + toString(this._reactionRateI_)
            + toString(this._tColon_)
            + toString(this._reactionRateIi_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tDoubleArrow_ == child)
        {
            this._tDoubleArrow_ = null;
            return;
        }

        if(this._reactant_ == child)
        {
            this._reactant_ = null;
            return;
        }

        if(this._tComma_ == child)
        {
            this._tComma_ = null;
            return;
        }

        if(this._reactionRateI_ == child)
        {
            this._reactionRateI_ = null;
            return;
        }

        if(this._tColon_ == child)
        {
            this._tColon_ = null;
            return;
        }

        if(this._reactionRateIi_ == child)
        {
            this._reactionRateIi_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tDoubleArrow_ == oldChild)
        {
            setTDoubleArrow((TTDoubleArrow) newChild);
            return;
        }

        if(this._reactant_ == oldChild)
        {
            setReactant((PReactant) newChild);
            return;
        }

        if(this._tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(this._reactionRateI_ == oldChild)
        {
            setReactionRateI((PReactionRateI) newChild);
            return;
        }

        if(this._tColon_ == oldChild)
        {
            setTColon((TTColon) newChild);
            return;
        }

        if(this._reactionRateIi_ == oldChild)
        {
            setReactionRateIi((PReactionRateIi) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
