/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ACrnSamplebody extends PSamplebody
{
    private PCrn _crn_;

    public ACrnSamplebody()
    {
        // Constructor
    }

    public ACrnSamplebody(
        @SuppressWarnings("hiding") PCrn _crn_)
    {
        // Constructor
        setCrn(_crn_);

    }

    @Override
    public Object clone()
    {
        return new ACrnSamplebody(
            cloneNode(this._crn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACrnSamplebody(this);
    }

    public PCrn getCrn()
    {
        return this._crn_;
    }

    public void setCrn(PCrn node)
    {
        if(this._crn_ != null)
        {
            this._crn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._crn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._crn_ == child)
        {
            this._crn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._crn_ == oldChild)
        {
            setCrn((PCrn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
