/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AEquiliProtocolbody extends PProtocolbody
{
    private PEquili _equili_;

    public AEquiliProtocolbody()
    {
        // Constructor
    }

    public AEquiliProtocolbody(
        @SuppressWarnings("hiding") PEquili _equili_)
    {
        // Constructor
        setEquili(_equili_);

    }

    @Override
    public Object clone()
    {
        return new AEquiliProtocolbody(
            cloneNode(this._equili_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEquiliProtocolbody(this);
    }

    public PEquili getEquili()
    {
        return this._equili_;
    }

    public void setEquili(PEquili node)
    {
        if(this._equili_ != null)
        {
            this._equili_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equili_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equili_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equili_ == child)
        {
            this._equili_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equili_ == oldChild)
        {
            setEquili((PEquili) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
