/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AFloatNumber extends PNumber
{
    private TTFloatType _tFloatType_;
    private TTString _tString_;
    private TTEqual _tEqual_;
    private PExpression _expression_;
    private PFloats _floats_;

    public AFloatNumber()
    {
        // Constructor
    }

    public AFloatNumber(
        @SuppressWarnings("hiding") TTFloatType _tFloatType_,
        @SuppressWarnings("hiding") TTString _tString_,
        @SuppressWarnings("hiding") TTEqual _tEqual_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") PFloats _floats_)
    {
        // Constructor
        setTFloatType(_tFloatType_);

        setTString(_tString_);

        setTEqual(_tEqual_);

        setExpression(_expression_);

        setFloats(_floats_);

    }

    @Override
    public Object clone()
    {
        return new AFloatNumber(
            cloneNode(this._tFloatType_),
            cloneNode(this._tString_),
            cloneNode(this._tEqual_),
            cloneNode(this._expression_),
            cloneNode(this._floats_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatNumber(this);
    }

    public TTFloatType getTFloatType()
    {
        return this._tFloatType_;
    }

    public void setTFloatType(TTFloatType node)
    {
        if(this._tFloatType_ != null)
        {
            this._tFloatType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tFloatType_ = node;
    }

    public TTString getTString()
    {
        return this._tString_;
    }

    public void setTString(TTString node)
    {
        if(this._tString_ != null)
        {
            this._tString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tString_ = node;
    }

    public TTEqual getTEqual()
    {
        return this._tEqual_;
    }

    public void setTEqual(TTEqual node)
    {
        if(this._tEqual_ != null)
        {
            this._tEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEqual_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public PFloats getFloats()
    {
        return this._floats_;
    }

    public void setFloats(PFloats node)
    {
        if(this._floats_ != null)
        {
            this._floats_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floats_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tFloatType_)
            + toString(this._tString_)
            + toString(this._tEqual_)
            + toString(this._expression_)
            + toString(this._floats_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tFloatType_ == child)
        {
            this._tFloatType_ = null;
            return;
        }

        if(this._tString_ == child)
        {
            this._tString_ = null;
            return;
        }

        if(this._tEqual_ == child)
        {
            this._tEqual_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._floats_ == child)
        {
            this._floats_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tFloatType_ == oldChild)
        {
            setTFloatType((TTFloatType) newChild);
            return;
        }

        if(this._tString_ == oldChild)
        {
            setTString((TTString) newChild);
            return;
        }

        if(this._tEqual_ == oldChild)
        {
            setTEqual((TTEqual) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._floats_ == oldChild)
        {
            setFloats((PFloats) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
