/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleReactant extends PReactant
{
    private PFactor _factor_;
    private TTMult _tMult_;
    private TTString _tString_;
    private TTPlus _tPlus_;
    private PReactant _reactant_;

    public AMultipleReactant()
    {
        // Constructor
    }

    public AMultipleReactant(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TTMult _tMult_,
        @SuppressWarnings("hiding") TTString _tString_,
        @SuppressWarnings("hiding") TTPlus _tPlus_,
        @SuppressWarnings("hiding") PReactant _reactant_)
    {
        // Constructor
        setFactor(_factor_);

        setTMult(_tMult_);

        setTString(_tString_);

        setTPlus(_tPlus_);

        setReactant(_reactant_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleReactant(
            cloneNode(this._factor_),
            cloneNode(this._tMult_),
            cloneNode(this._tString_),
            cloneNode(this._tPlus_),
            cloneNode(this._reactant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleReactant(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TTMult getTMult()
    {
        return this._tMult_;
    }

    public void setTMult(TTMult node)
    {
        if(this._tMult_ != null)
        {
            this._tMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tMult_ = node;
    }

    public TTString getTString()
    {
        return this._tString_;
    }

    public void setTString(TTString node)
    {
        if(this._tString_ != null)
        {
            this._tString_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tString_ = node;
    }

    public TTPlus getTPlus()
    {
        return this._tPlus_;
    }

    public void setTPlus(TTPlus node)
    {
        if(this._tPlus_ != null)
        {
            this._tPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPlus_ = node;
    }

    public PReactant getReactant()
    {
        return this._reactant_;
    }

    public void setReactant(PReactant node)
    {
        if(this._reactant_ != null)
        {
            this._reactant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._reactant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._tMult_)
            + toString(this._tString_)
            + toString(this._tPlus_)
            + toString(this._reactant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._tMult_ == child)
        {
            this._tMult_ = null;
            return;
        }

        if(this._tString_ == child)
        {
            this._tString_ = null;
            return;
        }

        if(this._tPlus_ == child)
        {
            this._tPlus_ = null;
            return;
        }

        if(this._reactant_ == child)
        {
            this._reactant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._tMult_ == oldChild)
        {
            setTMult((TTMult) newChild);
            return;
        }

        if(this._tString_ == oldChild)
        {
            setTString((TTString) newChild);
            return;
        }

        if(this._tPlus_ == oldChild)
        {
            setTPlus((TTPlus) newChild);
            return;
        }

        if(this._reactant_ == oldChild)
        {
            setReactant((PReactant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
