/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ANonzeroDisposePara extends PDisposePara
{
    private TTLParen _tLParen_;
    private PFactor _factor_;
    private TTRParen _tRParen_;

    public ANonzeroDisposePara()
    {
        // Constructor
    }

    public ANonzeroDisposePara(
        @SuppressWarnings("hiding") TTLParen _tLParen_,
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TTRParen _tRParen_)
    {
        // Constructor
        setTLParen(_tLParen_);

        setFactor(_factor_);

        setTRParen(_tRParen_);

    }

    @Override
    public Object clone()
    {
        return new ANonzeroDisposePara(
            cloneNode(this._tLParen_),
            cloneNode(this._factor_),
            cloneNode(this._tRParen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonzeroDisposePara(this);
    }

    public TTLParen getTLParen()
    {
        return this._tLParen_;
    }

    public void setTLParen(TTLParen node)
    {
        if(this._tLParen_ != null)
        {
            this._tLParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLParen_ = node;
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TTRParen getTRParen()
    {
        return this._tRParen_;
    }

    public void setTRParen(TTRParen node)
    {
        if(this._tRParen_ != null)
        {
            this._tRParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tLParen_)
            + toString(this._factor_)
            + toString(this._tRParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tLParen_ == child)
        {
            this._tLParen_ = null;
            return;
        }

        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._tRParen_ == child)
        {
            this._tRParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tLParen_ == oldChild)
        {
            setTLParen((TTLParen) newChild);
            return;
        }

        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._tRParen_ == oldChild)
        {
            setTRParen((TTRParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
