/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AOptermPower extends PPower
{
    private PParen _paren_;
    private TTPower _tPower_;
    private PPowerIn _powerIn_;

    public AOptermPower()
    {
        // Constructor
    }

    public AOptermPower(
        @SuppressWarnings("hiding") PParen _paren_,
        @SuppressWarnings("hiding") TTPower _tPower_,
        @SuppressWarnings("hiding") PPowerIn _powerIn_)
    {
        // Constructor
        setParen(_paren_);

        setTPower(_tPower_);

        setPowerIn(_powerIn_);

    }

    @Override
    public Object clone()
    {
        return new AOptermPower(
            cloneNode(this._paren_),
            cloneNode(this._tPower_),
            cloneNode(this._powerIn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOptermPower(this);
    }

    public PParen getParen()
    {
        return this._paren_;
    }

    public void setParen(PParen node)
    {
        if(this._paren_ != null)
        {
            this._paren_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paren_ = node;
    }

    public TTPower getTPower()
    {
        return this._tPower_;
    }

    public void setTPower(TTPower node)
    {
        if(this._tPower_ != null)
        {
            this._tPower_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPower_ = node;
    }

    public PPowerIn getPowerIn()
    {
        return this._powerIn_;
    }

    public void setPowerIn(PPowerIn node)
    {
        if(this._powerIn_ != null)
        {
            this._powerIn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._powerIn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paren_)
            + toString(this._tPower_)
            + toString(this._powerIn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paren_ == child)
        {
            this._paren_ = null;
            return;
        }

        if(this._tPower_ == child)
        {
            this._tPower_ = null;
            return;
        }

        if(this._powerIn_ == child)
        {
            this._powerIn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paren_ == oldChild)
        {
            setParen((PParen) newChild);
            return;
        }

        if(this._tPower_ == oldChild)
        {
            setTPower((TTPower) newChild);
            return;
        }

        if(this._powerIn_ == oldChild)
        {
            setPowerIn((PPowerIn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
