/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ARateSamplebody extends PSamplebody
{
    private PRate _rate_;

    public ARateSamplebody()
    {
        // Constructor
    }

    public ARateSamplebody(
        @SuppressWarnings("hiding") PRate _rate_)
    {
        // Constructor
        setRate(_rate_);

    }

    @Override
    public Object clone()
    {
        return new ARateSamplebody(
            cloneNode(this._rate_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARateSamplebody(this);
    }

    public PRate getRate()
    {
        return this._rate_;
    }

    public void setRate(PRate node)
    {
        if(this._rate_ != null)
        {
            this._rate_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rate_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rate_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rate_ == child)
        {
            this._rate_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rate_ == oldChild)
        {
            setRate((PRate) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
