/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ASampleinitInitializebody extends PInitializebody
{
    private PSample _sample_;

    public ASampleinitInitializebody()
    {
        // Constructor
    }

    public ASampleinitInitializebody(
        @SuppressWarnings("hiding") PSample _sample_)
    {
        // Constructor
        setSample(_sample_);

    }

    @Override
    public Object clone()
    {
        return new ASampleinitInitializebody(
            cloneNode(this._sample_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASampleinitInitializebody(this);
    }

    public PSample getSample()
    {
        return this._sample_;
    }

    public void setSample(PSample node)
    {
        if(this._sample_ != null)
        {
            this._sample_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sample_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sample_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sample_ == child)
        {
            this._sample_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sample_ == oldChild)
        {
            setSample((PSample) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
