/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AAltervalueSamplebody extends PSamplebody
{
    private PAltervalue _altervalue_;

    public AAltervalueSamplebody()
    {
        // Constructor
    }

    public AAltervalueSamplebody(
        @SuppressWarnings("hiding") PAltervalue _altervalue_)
    {
        // Constructor
        setAltervalue(_altervalue_);

    }

    @Override
    public Object clone()
    {
        return new AAltervalueSamplebody(
            cloneNode(this._altervalue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAltervalueSamplebody(this);
    }

    public PAltervalue getAltervalue()
    {
        return this._altervalue_;
    }

    public void setAltervalue(PAltervalue node)
    {
        if(this._altervalue_ != null)
        {
            this._altervalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._altervalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._altervalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._altervalue_ == child)
        {
            this._altervalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._altervalue_ == oldChild)
        {
            setAltervalue((PAltervalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
