/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class ANoTimestep extends PTimestep
{
    private PBitesize _bitesize_;

    public ANoTimestep()
    {
        // Constructor
    }

    public ANoTimestep(
        @SuppressWarnings("hiding") PBitesize _bitesize_)
    {
        // Constructor
        setBitesize(_bitesize_);

    }

    @Override
    public Object clone()
    {
        return new ANoTimestep(
            cloneNode(this._bitesize_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoTimestep(this);
    }

    public PBitesize getBitesize()
    {
        return this._bitesize_;
    }

    public void setBitesize(PBitesize node)
    {
        if(this._bitesize_ != null)
        {
            this._bitesize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bitesize_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bitesize_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bitesize_ == child)
        {
            this._bitesize_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bitesize_ == oldChild)
        {
            setBitesize((PBitesize) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
