/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class APlusOperator extends POperator
{
    private TTPlus _tPlus_;

    public APlusOperator()
    {
        // Constructor
    }

    public APlusOperator(
        @SuppressWarnings("hiding") TTPlus _tPlus_)
    {
        // Constructor
        setTPlus(_tPlus_);

    }

    @Override
    public Object clone()
    {
        return new APlusOperator(
            cloneNode(this._tPlus_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusOperator(this);
    }

    public TTPlus getTPlus()
    {
        return this._tPlus_;
    }

    public void setTPlus(TTPlus node)
    {
        if(this._tPlus_ != null)
        {
            this._tPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPlus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tPlus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tPlus_ == child)
        {
            this._tPlus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tPlus_ == oldChild)
        {
            setTPlus((TTPlus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
