/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.company.node;

import com.company.analysis.*;

@SuppressWarnings("nls")
public final class AWithTimestep extends PTimestep
{
    private TTEach _tEach_;
    private PFactor _factor_;
    private PBitesize _bitesize_;

    public AWithTimestep()
    {
        // Constructor
    }

    public AWithTimestep(
        @SuppressWarnings("hiding") TTEach _tEach_,
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") PBitesize _bitesize_)
    {
        // Constructor
        setTEach(_tEach_);

        setFactor(_factor_);

        setBitesize(_bitesize_);

    }

    @Override
    public Object clone()
    {
        return new AWithTimestep(
            cloneNode(this._tEach_),
            cloneNode(this._factor_),
            cloneNode(this._bitesize_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWithTimestep(this);
    }

    public TTEach getTEach()
    {
        return this._tEach_;
    }

    public void setTEach(TTEach node)
    {
        if(this._tEach_ != null)
        {
            this._tEach_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tEach_ = node;
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public PBitesize getBitesize()
    {
        return this._bitesize_;
    }

    public void setBitesize(PBitesize node)
    {
        if(this._bitesize_ != null)
        {
            this._bitesize_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bitesize_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tEach_)
            + toString(this._factor_)
            + toString(this._bitesize_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tEach_ == child)
        {
            this._tEach_ = null;
            return;
        }

        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._bitesize_ == child)
        {
            this._bitesize_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tEach_ == oldChild)
        {
            setTEach((TTEach) newChild);
            return;
        }

        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._bitesize_ == oldChild)
        {
            setBitesize((PBitesize) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
